language: c++
sudo: false
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - libssl-dev
      - libssh2-1-dev
cache:
  directories:
    - ${HOME}/dependencies
env:
  matrix:
    - LIBUV_VERSION=0.10.x EXACT_LIBUV_VERSION=0.10.36
    - LIBUV_VERSION=1.x EXACT_LIBUV_VERSION=1.7.5
install:
  - if [ ! -d "${HOME}/dependencies/libuv-${LIBUV_VERSION}" ]; then
      wget -q http://dist.libuv.org/dist/v${EXACT_LIBUV_VERSION}/libuv-v${EXACT_LIBUV_VERSION}.tar.gz;
      tar xzf libuv-v${EXACT_LIBUV_VERSION}.tar.gz;
      cd libuv-v${EXACT_LIBUV_VERSION};
      if [ "${LIBUV_VERSION}" == "0.10.x" ]; then
        make -j2;
        mkdir -p ${HOME}/dependencies/libuv-${LIBUV_VERSION}/lib;
        cp libuv* ${HOME}/dependencies/libuv-${LIBUV_VERSION}/lib;
        cp -r include ${HOME}/dependencies/libuv-${LIBUV_VERSION};
        cd ${HOME}/dependencies/libuv-${LIBUV_VERSION}/lib;
        ln -s libuv.so libuv.so.0.10;
      fi;
      if [ "${LIBUV_VERSION}" == "1.x" ]; then
        sh autogen.sh;
        ./configure --prefix=${HOME}/dependencies/libuv-${LIBUV_VERSION};
        make -j2 install;
      fi;
    else echo "Using Cached libuv v${LIBUV_VERSION}. Dependency does not need to be re-compiled";
    fi
  - cd ${TRAVIS_BUILD_DIR}
before_script:
  - EXTRA_CXX_FLAGS=
  - BUILD_EXAMPLES=ON
  - BUILD_TESTS=ON
  - if [ "$CXX" == "clang++" ]; then
      EXTRA_CXX_FLAGS="-Wno-unknown-warning-option";
      BUILD_EXAMPLES=OFF;
      BUILD_TESTS=OFF;
    fi
  - CXXFLAGS="${EXTRA_CXX_FLAGS}" cmake -DLIBUV_ROOT_DIR=${HOME}/dependencies/libuv-${LIBUV_VERSION}/ -DCASS_BUILD_STATIC=ON -DCASS_BUILD_EXAMPLES=${BUILD_EXAMPLES} -DCASS_BUILD_TESTS=${BUILD_TESTS} .
script:
  - make -j2
  - if [ "$CXX" != "clang++" ]; then
      test/unit_tests/cassandra_unit_tests;
    fi
