version: 1.x.{build}-{branch}
branches:
  except:
    - gh-pages
skip_tags: true
shallow_clone: false
cache:
  - C:\projects\dependencies\libs -> appveyor.yml
os: Visual Studio 2015
platform:
  - x86
  - x64
configuration:
#  - Debug
  - Release
environment:
  KERBEROS_VERSION: 4.1
  LIBSSH2_VERSION: 1.7.0
  LIBUV_VERSION: 1.8.0
  OPENSSL_VERSION: 1.0.2h
  DOWNLOADS_URL_PREFIX: http://downloads.datastax.com/cpp-driver/windows/dependencies
  TEST_DEPENDENCIES_DOWNLOAD_URL_PREFIX: https://raw.githubusercontent.com/mikefero/cpp-driver-msvc-libs/master
  DEPENDENCIES_LOCATION_PREFIX: C:/projects/dependencies/libs
  CONFIGURATION_COMPLETE: False
  matrix:
    - CMAKE_GENERATOR: Visual Studio 14 2015
      VISUAL_STUDIO_INTERNAL_VERSION: 140
      VISUAL_STUDIO_VERSION: 14.0
    - CMAKE_GENERATOR: Visual Studio 12 2013
      VISUAL_STUDIO_INTERNAL_VERSION: 120
      VISUAL_STUDIO_VERSION: 12.0
    - CMAKE_GENERATOR: Visual Studio 11 2012
      VISUAL_STUDIO_INTERNAL_VERSION: 110
      VISUAL_STUDIO_VERSION: 11.0
    - CMAKE_GENERATOR: Visual Studio 10 2010
      VISUAL_STUDIO_INTERNAL_VERSION: 100
      VISUAL_STUDIO_VERSION: 10.0

init:
  - ps: |
      # Determine the platform and create associate environment variables
      If ($env:Platform -Match "x86") {
        $env:ARCHITECTURE="32"
      } Else {
        $env:ARCHITECTURE="64"
        $env:CMAKE_GENERATOR_SUFFIX=" Win64"
      }
      $env:LIB_ARCHITECTURE="lib$($env:ARCHITECTURE)"
      $env:WINDOWS_ARCHITECTURE="win$($env:ARCHITECTURE)"

      # Generate the environment for the dependencies root directory
      $env:DEPENDENCIES_LOCATION="$($env:DEPENDENCIES_LOCATION_PREFIX)/$($env:Platform)/$($env:VISUAL_STUDIO_INTERNAL_VERSION)"

      # Generate the Kerberos environment variables
      $env:KERBEROS_ARCHIVE="kfw-$($env:KERBEROS_VERSION)-$($env:WINDOWS_ARCHITECTURE)-msvc100.zip"
      $env:KERBEROS_ROOT_DIR="$($env:DEPENDENCIES_LOCATION)/kfw-$($env:KERBEROS_VERSION)"

      # Generate the libssh2 environment variables
      $env:LIBSSH2_ARCHIVE="libssh2-$($env:LIBSSH2_VERSION)-$($env:WINDOWS_ARCHITECTURE)-msvc$($env:VISUAL_STUDIO_INTERNAL_VERSION).zip"
      $env:LIBSSH2_ROOT_DIR="$($env:DEPENDENCIES_LOCATION)/libssh2-$($env:LIBSSH2_VERSION)"

      # Generate the libuv environment variables
      $env:LIBUV_ARCHIVE="libuv-$($env:LIBUV_VERSION)-$($env:WINDOWS_ARCHITECTURE)-msvc$($env:VISUAL_STUDIO_INTERNAL_VERSION).zip"
      $env:LIBUV_ROOT_DIR="$($env:DEPENDENCIES_LOCATION)/libuv-$($env:LIBUV_VERSION)"

      # Generate the OpenSSL environment variables
      $env:OPENSSL_ARCHIVE="openssl-$($env:OPENSSL_VERSION)-$($env:WINDOWS_ARCHITECTURE)-msvc$($env:VISUAL_STUDIO_INTERNAL_VERSION).zip"
      $env:OPENSSL_ROOT_DIR="$($env:DEPENDENCIES_LOCATION)/openssl-$($env:OPENSSL_VERSION)"

      # Generate the archive name for the driver artifact
      $env:DRIVER_ARTIFACT_ARCHIVE="dse-cpp-driver-ci-artifact-$env:APPVEYOR_BUILD_VERSION-win$env:ARCHITECTURE-msvc$env:VISUAL_STUDIO_INTERNAL_VERSION.zip"

install:
  - ps: |
      # Install the dependencies (if needed)
      New-Item -ItemType Directory -Force -Path "$($env:DEPENDENCIES_LOCATION)"
      Push-Location "$($env:DEPENDENCIES_LOCATION)"

      # Determine if Kerberos for Windows should be installed (cached)
      If (!(Test-Path -Path "kfw-$($env:KERBEROS_VERSION)")) {
        # Download and extract the dependency
        Start-FileDownload "$($env:TEST_DEPENDENCIES_DOWNLOAD_URL_PREFIX)/kerberos/$($env:KERBEROS_VERSION)/$($env:KERBEROS_ARCHIVE)" -FileName $env:KERBEROS_ARCHIVE
        7z -o"kfw-$($env:KERBEROS_VERSION)" x $env:KERBEROS_ARCHIVE

        # Delete the binary archive
        Remove-Item $env:KERBEROS_ARCHIVE
      }

      # Determine if libssh2 should be installed (cached)
      If (!(Test-Path -Path "libssh2-$($env:LIBSSH2_VERSION)")) {
        # Download and extract the dependency
        #Start-FileDownload "$($env:DOWNLOADS_URL_PREFIX)/libssh2/v$($env:LIBSSH2_VERSION)/$($env:LIBSSH2_ARCHIVE)" -FileName $env:LIBSSH2_ARCHIVE
        Start-FileDownload "$($env:TEST_DEPENDENCIES_DOWNLOAD_URL_PREFIX)/libssh2/$($env:LIBSSH2_VERSION)/$($env:LIBSSH2_ARCHIVE)" -FileName $env:LIBSSH2_ARCHIVE
        7z -o"libssh2-$($env:LIBSSH2_VERSION)" x $env:LIBSSH2_ARCHIVE

        # Delete the binary archive
        Remove-Item $env:LIBSSH2_ARCHIVE
      }

      # Determine if libuv should be installed (cached)
      If (!(Test-Path -Path "libuv-$($env:LIBUV_VERSION)")) {
        # Download and extract the dependency
        #Start-FileDownload "$($env:DOWNLOADS_URL_PREFIX)/libuv/v$($env:LIBUV_VERSION)/$($env:LIBUV_ARCHIVE)" -FileName $env:LIBUV_ARCHIVE
        Start-FileDownload "$($env:TEST_DEPENDENCIES_DOWNLOAD_URL_PREFIX)/libuv/$($env:LIBUV_VERSION)/$($env:LIBUV_ARCHIVE)" -FileName $env:LIBUV_ARCHIVE
        7z -o"libuv-$($env:LIBUV_VERSION)" x $env:LIBUV_ARCHIVE

        # Only keep the static libraries
        Move-Item "libuv-$($env:LIBUV_VERSION)/static/lib" "libuv-$($env:LIBUV_VERSION)/lib"
        Remove-Item "libuv-$($env:LIBUV_VERSION)/static" -Force -Recurse
        Remove-Item "libuv-$($env:LIBUV_VERSION)/shared" -Force -Recurse

        # Delete the binary archive
        Remove-Item $env:LIBUV_ARCHIVE
      }

      # Determine if OpenSSL should be installed (cached)
      If (!(Test-Path -Path "openssl-$($env:OPENSSL_VERSION)")) {
        # Download and extract the dependency
        #Start-FileDownload "$($env:DOWNLOADS_URL_PREFIX)/openssl/v$($env:OPENSSL_VERSION)/$($env:OPENSSL_ARCHIVE)" -FileName $env:OPENSSL_ARCHIVE
        Start-FileDownload "$($env:TEST_DEPENDENCIES_DOWNLOAD_URL_PREFIX)/openssl/$($env:OPENSSL_VERSION)/$($env:OPENSSL_ARCHIVE)" -FileName $env:OPENSSL_ARCHIVE
        7z -o"openssl-$($env:OPENSSL_VERSION)" x $env:OPENSSL_ARCHIVE

        # Only keep the static libaries
        Move-Item "openssl-$($env:OPENSSL_VERSION)/static/lib" "openssl-$($env:OPENSSL_VERSION)/lib"
        Remove-Item "openssl-$($env:OPENSSL_VERSION)/static" -Force -Recurse
        Remove-Item "openssl-$($env:OPENSSL_VERSION)/shared" -Force -Recurse

        # Delete the binary archive
        Remove-Item $env:OPENSSL_ARCHIVE
      }

      # Remove pre-installed OpenSSL (resolve conflicts)
      Remove-Item "C:/OpenSSL-*" -Force -Recurse

      # Move back to original directory
      Pop-Location

before_build:
  - ps: |
      # Create and navigate to the build directory (build outside tree)
      New-Item -ItemType Directory -Force -Path build
      Push-Location build

      # Configure the build via CMake
      cmake -G "$($env:CMAKE_GENERATOR)$($env:CMAKE_GENERATOR_SUFFIX)" -DCMAKE_INSTALL_PREFIX=lib -DCASS_MULTICORE_COMPILATION=ON -DCMAKE_BUILD_TYPE=$env:CONFIGURATION -DDSE_BUILD_STATIC=ON -DDSE_USE_STATIC_LIBS=ON -DDSE_BUILD_EXAMPLES=ON -DDSE_BUILD_TESTS=ON -DDSE_USE_LIBSSH2=ON ..

      # Move back to working directory
      Pop-Location

build_script:
  - ps: $env:CONFIGURATION_COMPLETE=$TRUE
  - ps: cmake --build build --config "$($env:CONFIGURATION)"

after_build:
  - ps: |
      # Create the artifact structure for the driver
      New-Item -ItemType Directory -Force -Path $env:TEMP/cpp-driver-dse-artifact/bin
      Copy-Item build/$env:CONFIGURATION/dse.dll $env:TEMP/cpp-driver-dse-artifact/bin
      New-Item -ItemType Directory -Force -Path $env:TEMP/cpp-driver-dse-artifact/include
      Copy-Item include/* $env:TEMP/cpp-driver-dse-artifact/include
      New-Item -ItemType Directory -Force -Path $env:TEMP/cpp-driver-dse-artifact/lib
      Copy-Item build/$env:CONFIGURATION/dse.lib $env:TEMP/cpp-driver-dse-artifact/lib
      Copy-Item build/$env:CONFIGURATION/dse_static.lib $env:TEMP/cpp-driver-dse-artifact/lib

      # Create the driver archive artifact
      7z a -tzip $env:DRIVER_ARTIFACT_ARCHIVE -r $env:TEMP/cpp-driver-dse-artifact/*

      # Publish/Upload the artifacts to AppVeyor (Artifacts tab in UI)
      Push-AppveyorArtifact $env:DRIVER_ARTIFACT_ARCHIVE -DeploymentName "DataStax C/C++ DSE Driver"
      Push-AppveyorArtifact build/$env:CONFIGURATION/dse-integration-tests.exe -DeploymentName "DataStax C/C++ DSE Driver Integration Tests"
      Push-AppveyorArtifact build/$env:CONFIGURATION/dse-unit-tests.exe -DeploymentName "DataStax C/C++ DSE Driver Unit Tests"

test_script:
  - ps: Start-Process -FilePath "build/$env:CONFIGURATION/dse-unit-tests.exe" -ArgumentList "--gtest_output=xml:unit-tests-gtest-results.xml" -Wait -NoNewWindow

on_finish:
  - ps: (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unit-tests-gtest-results.xml))

on_failure:
  - ps: |
      # Write the CMake output and error logs to the console
      If ($env:CONFIGURATION_COMPLETE -eq "False") {
        If (Test-Path build/CMakeFiles/CMakeOutput.log) {
          Write-Output "CMakeOutput.log"
          cat build/CMakeFiles/CMakeOutput.log
        }
        If (Test-Path build/CMakeFiles/CMakeError.log) {
          Write-Output "CMakeError.log"
          cat build/CMakeFiles/CMakeError.log
        }
      }